export const DATA = [
  {
    latitude: -33.875,
    longitude: 151.125,
    generationtime_ms: 0.244736671447754,
    utc_offset_seconds: 39600,
    timezone: "Australia/Sydney",
    timezone_abbreviation: "GMT+11",
    elevation: 82,
    current_units: {
      time: "iso8601",
      interval: "seconds",
      temperature_2m: "°C",
      relative_humidity_2m: "%",
      apparent_temperature: "°C",
      wind_speed_10m: "km/h",
      cloud_cover: "%",
      pressure_msl: "hPa",
      is_day: "",
      precipitation: "mm",
    },
    current: {
      time: "2026-04-03T10:15",
      interval: 900,
      temperature_2m: 20.6,
      relative_humidity_2m: 79,
      apparent_temperature: 30,
      wind_speed_10m: 3.8,
      cloud_cover: 34,
      pressure_msl: 1022.9,
      is_day: 1,
      precipitation: 0,
    },
    daily_units: {
      time: "iso8601",
      uv_index_max: "",
      sunset: "iso8601",
      weather_code: "wmo code",
      shortwave_radiation_sum: "MJ/m²",
      precipitation_sum: "mm",
    },
    daily: {
      time: ["2026-04-03"],
      uv_index_max: [5.55],
      sunset: ["2026-04-03T18:48"],
      weather_code: [45],
      shortwave_radiation_sum: [15.09],
      precipitation_sum: [0.1],
    },
  },
  {
    latitude: -33.75,
    longitude: 151,
    generationtime_ms: 0.172138214111328,
    utc_offset_seconds: 39600,
    timezone: "Australia/Sydney",
    timezone_abbreviation: "GMT+11",
    elevation: 114,
    location_id: 1,
    current_units: {
      time: "iso8601",
      interval: "seconds",
      temperature_2m: "°C",
      relative_humidity_2m: "%",
      apparent_temperature: "°C",
      wind_speed_10m: "km/h",
      cloud_cover: "%",
      pressure_msl: "hPa",
      is_day: "",
      precipitation: "mm",
    },
    current: {
      time: "2026-04-03T10:15",
      interval: 900,
      temperature_2m: 19.7,
      relative_humidity_2m: 80,
      apparent_temperature: 20.9,
      wind_speed_10m: 6.9,
      cloud_cover: 47,
      pressure_msl: 1023,
      is_day: 1,
      precipitation: 0,
    },
    daily_units: {
      time: "iso8601",
      uv_index_max: "",
      sunset: "iso8601",
      weather_code: "wmo code",
      shortwave_radiation_sum: "MJ/m²",
      precipitation_sum: "mm",
    },
    daily: {
      time: ["2026-04-03"],
      uv_index_max: [6.2],
      sunset: ["2026-04-03T18:49"],
      weather_code: [45],
      shortwave_radiation_sum: [15.29],
      precipitation_sum: [0],
    },
  },
  {
    latitude: -33.75,
    longitude: 151,
    generationtime_ms: 0.153660774230957,
    utc_offset_seconds: 39600,
    timezone: "Australia/Sydney",
    timezone_abbreviation: "GMT+11",
    elevation: 62,
    location_id: 2,
    current_units: {
      time: "iso8601",
      interval: "seconds",
      temperature_2m: "°C",
      relative_humidity_2m: "%",
      apparent_temperature: "°C",
      wind_speed_10m: "km/h",
      cloud_cover: "%",
      pressure_msl: "hPa",
      is_day: "",
      precipitation: "mm",
    },
    current: {
      time: "2026-04-03T10:15",
      interval: 900,
      temperature_2m: 20.1,
      relative_humidity_2m: 80,
      apparent_temperature: 21.3,
      wind_speed_10m: 6.9,
      cloud_cover: 47,
      pressure_msl: 1023,
      is_day: 1,
      precipitation: 0,
    },
    daily_units: {
      time: "iso8601",
      uv_index_max: "",
      sunset: "iso8601",
      weather_code: "wmo code",
      shortwave_radiation_sum: "MJ/m²",
      precipitation_sum: "mm",
    },
    daily: {
      time: ["2026-04-03"],
      uv_index_max: [6.35],
      sunset: ["2026-04-03T18:49"],
      weather_code: [45],
      shortwave_radiation_sum: [15.29],
      precipitation_sum: [0],
    },
  },
  {
    latitude: 28.625,
    longitude: 77.375,
    generationtime_ms: 0.138640403747559,
    utc_offset_seconds: 39600,
    timezone: "Australia/Sydney",
    timezone_abbreviation: "GMT+11",
    elevation: 206,
    location_id: 3,
    current_units: {
      time: "iso8601",
      interval: "seconds",
      temperature_2m: "°C",
      relative_humidity_2m: "%",
      apparent_temperature: "°C",
      wind_speed_10m: "km/h",
      cloud_cover: "%",
      pressure_msl: "hPa",
      is_day: "",
      precipitation: "mm",
    },
    current: {
      time: "2026-04-03T10:15",
      interval: 900,
      temperature_2m: 23.6,
      relative_humidity_2m: 71,
      apparent_temperature: 26,
      wind_speed_10m: 3.2,
      cloud_cover: 100,
      pressure_msl: 1006.6,
      is_day: 0,
      precipitation: 0,
    },
    daily_units: {
      time: "iso8601",
      uv_index_max: "",
      sunset: "iso8601",
      weather_code: "wmo code",
      shortwave_radiation_sum: "MJ/m²",
      precipitation_sum: "mm",
    },
    daily: {
      time: ["2026-04-03"],
      uv_index_max: [6.35],
      sunset: ["2026-04-04T00:09"],
      weather_code: [80],
      shortwave_radiation_sum: [19.22],
      precipitation_sum: [0.7],
    },
  },
];
